### PR TITLE
fix unaligned pointer access

### LINKED ISSUE #3: bug: pointer is not aligned in entry slice
toolchain: nightly-20240411

```
--- STDERR:              risingwave_connector parser::debezium::simd_json_parser::tests::test3_postgres::test_other_types ---
thread 'parser::debezium::simd_json_parser::tests::test3_postgres::test_other_types' panicked at library/core/src/panicking.rs:215:5:
unsafe precondition(s) violated: slice::from_raw_parts requires the pointer to be aligned and non-null, and the total size of the slice not to exceed `isize::MAX`
stack backtrace:
   0: rust_begin_unwind
             at /rustc/aa067fb984d36462548bb785da221bfaf38253f0/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_nounwind_fmt::runtime
             at /rustc/aa067fb984d36462548bb785da221bfaf38253f0/library/core/src/panicking.rs:110:18
   2: core::panicking::panic_nounwind_fmt
             at /rustc/aa067fb984d36462548bb785da221bfaf38253f0/library/core/src/panicking.rs:120:5
   3: core::panicking::panic_nounwind
             at /rustc/aa067fb984d36462548bb785da221bfaf38253f0/library/core/src/panicking.rs:215:5
   4: core::slice::raw::from_raw_parts::precondition_check
             at /rustc/aa067fb984d36462548bb785da221bfaf38253f0/library/core/src/ub_checks.rs:66:21
   5: core::slice::raw::from_raw_parts
             at /rustc/aa067fb984d36462548bb785da221bfaf38253f0/library/core/src/slice/raw.rs:96:9
   6: jsonbb::value_ref::ObjectRef::entries
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jsonbb-0.1.3/src/value_ref.rs:680:18
   7: jsonbb::value_ref::ObjectRef::iter
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jsonbb-0.1.3/src/value_ref.rs:631:9
   8: jsonbb::serde::<impl serde::ser::Serialize for jsonbb::value_ref::ObjectRef>::serialize
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jsonbb-0.1.3/src/serde.rs:89:23
   9: jsonbb::serde::<impl serde::ser::Serialize for jsonbb::value_ref::ValueRef>::serialize
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jsonbb-0.1.3/src/serde.rs:53:32
  10: <risingwave_common::types::jsonb::JsonbRef as risingwave_common::types::to_text::ToText>::write
             at /rc20/github/risingwavelabs/risingwave/src/common/src/types/jsonb.rs:115:9
  11: <risingwave_common::types::jsonb::JsonbRef as risingwave_common::types::to_text::ToText>::write_with_type
             at /rc20/github/risingwavelabs/risingwave/src/common/src/types/jsonb.rs:123:9
  12: risingwave_common::types::jsonb::JsonbRef::force_str
             at /rc20/github/risingwavelabs/risingwave/src/common/src/types/jsonb.rs:323:17
  13: risingwave_connector::parser::debezium::simd_json_parser::tests::assert_json_eq
             at ./src/parser/debezium/simd_json_parser.rs:113:13
  14: risingwave_connector::parser::debezium::simd_json_parser::tests::test3_postgres::test_other_types::{{closure}}
             at ./src/parser/debezium/simd_json_parser.rs:752:13
  15: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/aa067fb984d36462548bb785da221bfaf38253f0/library/core/src/future/future.rs:123:9
  16: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/instrument.rs:321:9
  17: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/aa067fb984d36462548bb785da221bfaf38253f0/library/core/src/future/future.rs:123:9
  18: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:659:57
  19: tokio::runtime::coop::with_budget
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/coop.rs:107:5
  20: tokio::runtime::coop::budget
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/coop.rs:73:5
  21: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}::{{closure}}
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:659:25
  22: tokio::runtime::scheduler::current_thread::Context::enter
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:404:19
  23: tokio::runtime::scheduler::current_thread::CoreGuard::block_on::{{closure}}
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:658:36
  24: tokio::runtime::scheduler::current_thread::CoreGuard::enter::{{closure}}
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:737:68
  25: tokio::runtime::context::scoped::Scoped<T>::set
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context/scoped.rs:40:9
  26: tokio::runtime::context::set_scheduler::{{closure}}
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context.rs:176:26
  27: std::thread::local::LocalKey<T>::try_with
             at /rustc/aa067fb984d36462548bb785da221bfaf38253f0/library/std/src/thread/local.rs:284:16
  28: std::thread::local::LocalKey<T>::with
             at /rustc/aa067fb984d36462548bb785da221bfaf38253f0/library/std/src/thread/local.rs:260:9
  29: tokio::runtime::context::set_scheduler
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context.rs:176:9
  30: tokio::runtime::scheduler::current_thread::CoreGuard::enter
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:737:27
  31: tokio::runtime::scheduler::current_thread::CoreGuard::block_on
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:646:19
  32: tokio::runtime::scheduler::current_thread::CurrentThread::block_on::{{closure}}
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:175:28
  33: tokio::runtime::context::runtime::enter_runtime
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/context/runtime.rs:65:16
  34: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/scheduler/current_thread/mod.rs:167:9
  35: tokio::runtime::runtime::Runtime::block_on
             at /home/mrcroxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.37.0/src/runtime/runtime.rs:349:47
  36: risingwave_connector::parser::debezium::simd_json_parser::tests::test3_postgres::test_other_types
             at ./src/parser/debezium/simd_json_parser.rs:765:13
  37: risingwave_connector::parser::debezium::simd_json_parser::tests::test3_postgres::test_other_types::{{closure}}
             at ./src/parser/debezium/simd_json_parser.rs:712:36
  38: core::ops::function::FnOnce::call_once
             at /rustc/aa067fb984d36462548bb785da221bfaf38253f0/library/core/src/ops/function.rs:250:5
  39: core::ops::function::FnOnce::call_once
             at /rustc/aa067fb984d36462548bb785da221bfaf38253f0/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread caused non-unwinding panic. aborting.
```

### PR DESCRIPTION
**Pull request by wangrunji0408**
fix #3 and release v0.1.4

### CODE REVIEW

File: src/partial_eq.rs [hunk 1]
```diff
@@ -1,7 +1,22 @@
+// Copyright 2023 RisingWave Labs
```
Comment (MrCroxx) [inline src/partial_eq.rs]:
```suggestion
// Copyright 2024 RisingWave Labs
```

**Review by MrCroxx — APPROVED** [review]
LGTM
